### ISSUE TITLE
Importing barbarian adds both barbarian and monk versions of Unarmored Defence as DAE passive effects, causing wrong AC calculation

### ISSUE THREAD

**Issue by Kirsham** [MrPrimate/ddb-importer#186]
When importing a barbarian, both "Unarmored Defence (barbarian)" and "Unarmored Defence (monk)" are added as DAE passive effects. The AC appears to be calculated from the monk version rather than the barbarian version, causing the AC to be wrong. Manually disabling the monk version of the active effect fixes the issue.

**Comment by MrPrimate** [comment]
What version of DAE, DAE SRD/Midi SRD, 5e, Foundy and DDB Importer are you using? These should be fixed using the latest versions.

**Comment by Kirsham** [comment]
My initial post was made with the following module versions:

Dynamic Active Effects SRD v6.0.01
Dynamic effects using Active Effects v0.8.69
Midi QOL v0.8.86
Midi SRD v0.1.03

I updated my modules, only Midi QOL was not up to date. The issue persists when updating to the current version (v0.8.90).

I see. I suppose that's outside your project, thanks nonetheless!

**Comment by emirkmo** [comment]
This has been a long known issue, in fact, MrPrimate himself helped me diagnose and "fix" it about 6 months ago. It's an issue with SRD. Technically, the module could have a post import hack that goes through any barbarian or monk (or anyone with natural armor) and fixes it. Alternatively, a warning should be displayed for monks and barbarians on import to check the active version of natural armor, at least for player characters.

**Comment by MrPrimate** [comment]
Hopefully fixed in latest versuion

**Comment by Kirsham** [comment]
Just updated my modules and tested the import again, but the issue persists I'm afraid. 

D&D Beyond Importer v2.7.0
Dynamic Active Effects SRD v6.0.01
Dynamic effects using Active Effects v0.8.71
Midi QOL v0.8.94
Midi SRD v0.1.03

**Comment by MrPrimate** [comment]
@Kirsham do you have retain active effects ticked? That will retain any effects on the character currently. Can you try deleting the two effects on the character and reimporting.

**Comment by Kirsham** [comment]
I didn't have active effects ticked and I believe I had deleted the monk effect, but keeping the barbarian effect. At any rate, I tried again just now and it appears to be fixed! I don't really know what I did differently this morning compared to last night, but whatever the case it seems to be working now. I also tried to import a monk character to test that it works that way too, and I'm happy to say it does. Thanks a lot!

**Comment by emirkmo** [comment]
@Kirsham Can you share your active effects settings so I can replicate your success? :1st_place_medal:

**Comment by Kirsham** [comment]
Sure, here they are:

[x] Non-transfer effects require item targets (dnd5e)
[x] Use the DAE Active Effect Config Sheet
[  ] No Duplicate Damage macros
[x] Expire timed effects in real time
[  ] Include active effects in special traits display
[  ] Use ability save field when rolling ability saves
[  ] Display results of inline rolls
[  ] Confirm effect deletions
[x] DAE Title Bar
Amount of debug to show: None
[  ] Show Deprecation Erros
[  ] Disable all active effect processing
